/**:
  ros__parameters:
    device_name: /dev/ttyUSB0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"

/modbus_rtu_driver_node:
  ros__parameters:
    id: 0x50
    frame_link: base_link
